namespace LightningArc.Utils.Data.ADO.SqlBuilder.Definitions;

/// <summary>
/// Represents the mapping and metadata definition for a database column.
/// </summary>
public class ColumnDefinition
{
    /// <summary>
    /// Gets the name of the column in the database.
    /// </summary>
    public string ColumnName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the name of the property in the C# model.
    /// </summary>
    public string PropertyName { get; init; } = string.Empty;

    /// <summary>
    /// Gets a value indicating whether this column is a primary key or part of a composite key.
    /// </summary>
    public bool IsKey { get; init; }

    /// <summary>
    /// Gets a value indicating whether the column's value is generated by the database (e.g., Identity, Sequence).
    /// </summary>
    public bool IsDatabaseGenerated { get; init; }

    /// <summary>
    /// Gets a value indicating whether the column's value is computed by the database.
    /// </summary>
    public bool IsComputed { get; init; }

    /// <summary>
    /// Gets the sorting definition for this column, if applicable.
    /// </summary>
    public OrderDefinition? Order { get; init; }
}
